export const EVENT_FETCH_ANSWER_IMAGE = 'EVENT_FETCH_ANSWER_IMAGE';
export const EVENT_FETCH_ORIGIN_IMAGE = 'EVENT_FETCH_ORIGIN_IMAGE';
export const EVENT_INIT_DATA = 'EVENT_INIT_DATA';
export const EVENT_INIT_BOARD_VIEW = 'EVENT_INIT_BOARD_VIEW';
export const EVENT_INIT_PUZZLES_VIEW = 'EVENT_INIT_PUZZLES_VIEW';
export const EVENT_UPDATE_PUZZLE_VIEW = 'EVENT_UPDATE_PUZZLE_VIEW';
export const EVENT_UPDATE_HINT_VIEW = 'EVENT_UPDATE_HINT_VIEW'
export const EVENT_RESIZE_BOARD_VIEW = 'EVENT_RESIZE_BOARD_VIEW';

export const EVENT_START_TOUCH_PUZZLE = 'EVENT_START_TOUCH_PUZZLE';
export const EVENT_END_TOUCH_PUZZLE = 'EVENT_END_TOUCH_PUZZLE';

export const EVENT_START_TIMER = 'EVENT_START_TIMER';
export const EVENT_STOP_TIMER = 'EVENT_STOP_TIMER';
export const EVENT_UPDATE_TIMER = 'EVENT_UPDATE_TIMER';

export const EVENT_INIT_TOUCH_PUZZLE = 'EVENT_INIT_TOUCH_PUZZLE';
export const EVENT_REMOVE_TOUCH_PUZZLE = 'EVENT_REMOVE_TOUCH_PUZZLE';

export const EVENT_INIT_PINCH = 'EVENT_INIT_PINCH';
export const EVENT_REMOVE_PINCH = 'EVENT_REMOVE_PINCH';

export const EVENT_START_PUZZLE = 'EVENT_START_PUZZLE';
export const EVENT_COMPLETE_PUZZLE = 'EVENT_COMPLETE_PUZZLE';

export const EVENT_PLAY_START = 'EVENT_PLAY_START';
export const EVENT_PLAY_CLEAR = 'EVENT_PLAY_CLEAR';
export const EVENT_PLAY_RESULT = 'EVENT_PLAY_RESULT';
export const EVENT_PLAY_CLEAR_X = 'EVENT_PLAY_CLEAR_X';
export const EVENT_PLAY_COLORIZE = 'EVENT_PLAY_COLORIZE';
export const EVENT_PLAY_FULL_COLORIZE = 'EVENT_PLAY_FULL_COLORIZE';
export const EVENT_PLAY_CLEAN_BACKGROUND = 'EVENT_PLAY_CLEAN_BACKGROUND';
export const EVENT_PLAT_CLEAN_HEAD_UP_DISPLAY = 'EVENT_PLAT_CLEAN_HEAD_UP_DISPLAY';

export const EVENT_UPDATE_LOCK = 'EVENT_UPDATE_LOCK';
export const EVENT_UPDATE_ROW_HINT_VIEW_SOLVED = 'EVENT_UPDATE_ROW_HINT_VIEW_SOLVED';
export const EVENT_UPDATE_COLUMN_HINT_VIEW_SOLVED = 'EVENT_UPDATE_COLUMN_HINT_VIEW_SOLVED';

export const EVENT_SAVE_PUZZLE = 'EVENT_SAVE_PUZZLE';
